site_name: OMOP LLM
site_description: LLM interface for the OMOP Graph project for easy LLM tooling.
site_url: https://AustralianCancerDataNetwork.github.io/omop-llm
repo_url: https://github.com/AustralianCancerDataNetwork/omop-llm
repo_name: omop-llm

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
      - Installation: usage/installation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_root_heading: true
            show_source: false
  - table-reader

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables